/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    fontFamily: {
      sans: ['Alan Sans', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial'],
      montserrat: ['Montserrat', 'ui-sans-serif', 'system-ui'],
      headline: ["Manrope"],
      body: ["Inter"],
      label: ["Inter"]
    },
    screens: {
      bgpc: { max: "2400px" },
      pc: { max: "1800px" },
      tablet: { max: "900px" },
      phone: { max: "540px" },
    },
    extend: {
      colors: {
        lightgreen:"#F4FFF4",
        green:"#057003",
        darkgreen:"#80AA4F",
        graySubHd: "#535353",
        grayFooter:"#393939",
        teal: "#0f5661",
        lightTeal: "#ecf7f3",
        "on-surface": "#001d32",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#001d33",
        "tertiary-fixed-dim": "#ffb690",
        "surface-container": "#e3efff",
        "on-tertiary-fixed": "#341100",
        "surface": "#f7f9ff",
        "surface-tint": "#49607c",
        "outline-variant": "#c4c6cf",
        "on-surface-variant": "#43474e",
        "on-tertiary-container": "#fe771b",
        "outline": "#74777f",
        "on-primary-fixed-variant": "#314863",
        "on-primary": "#ffffff",
        "secondary-container": "#bfddfe",
        "surface-bright": "#f7f9ff",
        "surface-container-low": "#edf4ff",
        "background": "#f7f9ff",
        "error-container": "#ffdad6",
        "surface-container-high": "#d8eaff",
        "on-error-container": "#93000a",
        "primary-container": "#1f3751",
        "inverse-primary": "#b0c9e8",
        "secondary-fixed-dim": "#accaea",
        "primary-fixed": "#d1e4ff",
        "on-primary-fixed": "#011d35",
        "on-secondary-fixed-variant": "#2c4964",
        "surface-container-highest": "#cee5ff",
        "inverse-on-surface": "#e8f2ff",
        "secondary": "#44617d",
        "on-background": "#001d32",
        "tertiary": "#3b1500",
        "secondary-fixed": "#cee5ff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#5d2500",
        "tertiary-fixed": "#ffdbca",
        "on-tertiary-fixed-variant": "#783200",
        "on-secondary-container": "#45627e",
        "on-primary-container": "#89a1bf",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#b0c9e8",
        "surface-dim": "#c1ddfb",
        "inverse-surface": "#16334a",
        "surface-variant": "#cee5ff",
        "primary": "#06223a"
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic':
          'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      keyframes: {
        appear: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        bounce: {
          "0%": {
            transform: "scale(0.8)",
          },
          "100%": {
            transform: "scale(1)",
          },
        },
        drop: {
          "0%": { top: "-100px" },
          "100%": { top: "0px" },
        },
        twirl: {
          "0%": { transform: "translateY(100%)" },
        },
      },
      animation: {
        drop: "drop 1.2s ease-in",
        appear: "appear 1.2s ease-in",
        twirlf: "twirl 0.2s ease-in forwards",
        twirlb: "twirl 0.2s 0.2s ease-out forwards reverse",
      },
    },
  },
  variants: {
    extend: {
      backgroundColor: ["active"],
      animation: ["hover", "focus"],
      transform: ["hover"],
    },
  },
  plugins: [],
}
